### ISSUE TITLE
Simulate networks with more orgs

### ISSUE THREAD

**Issue by bboston7** [stellar/supercluster#210]
```[tasklist]
### Tasks
- [x] Generate 16-org graph based on pubnet survey data
- [x] Identify op type distributions + byte sizes for realistic traffic modeling
- [ ] https://github.com/stellar/supercluster/pull/220
```

Some additional requirements:
* Additional orgs added to create 16 org graph must look like existing orgs
  * Similar connectivity, latency, number of nodes per org, etc
* Inject load from watchers
* Use symmetric quorum sets
* Derive apply time distribution per-op based on the replay of a recent ledger segment
* Use per-connection latency data from most recent survey

For more info, see [this doc](https://docs.google.com/document/d/183GcFRT-q0qEH2I-4lcVQcpVEd51HS8wUAV-W6TjCUE/edit?usp=sharing).
